import Head from "next/head";
import ClassroomCards from "../src/components/ClassroomCards";
import Navbar from "../src/components/navbar";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main className="mt-4">
        <ClassroomCards />
      </main>
    </div>
  );
}
